import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/Providers";
import ErrorProvider from "@/components/ErrorProvider";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={cn("bg-black", roboto.className)}>
				<Providers>
					<NextIntlClientProvider messages={messages}>
						<ErrorProvider />
						{children}
					</NextIntlClientProvider>
				</Providers>
			</body>
		</html>
	);
}
