import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import ErrorProvider from "@/components/ErrorProvider";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
	style: ["normal", "italic"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`bg-transparent ${roboto.className}`}>
				<Providers>
					<NextIntlClientProvider messages={messages}>
						<Suspense>
							<ErrorProvider />
						</Suspense>
						<TooltipProvider>{children}</TooltipProvider>
						<Toaster />
					</NextIntlClientProvider>
				</Providers>
			</body>
		</html>
	);
}
